from component import Comp, Port


class Tunnel(Comp):
    """
    Tunnel is used to combine two ports in a simple way.
    """
    
    def __init__(self, width: int, label: str, output: bool, loc=None):
        """
        Parameter:
        output set to true means the tunnel port is used as the source of a
        data stream.
        """
        super(Tunnel, self).__init__("Tunnel", Comp.Lib.WIRING)
        self.width = width
        self.label = label
        if output == True:
            self.facing = Comp.Facing.EAST
        else:
            self.facing = Comp.Facing.WEST
        self.loc = loc


class Circuit(object):
    """
    Circuit locate the components according to the graph generated by paser.
    """

    def __init__(self):
        pass